contexts:
- data:
    output_dir: node-consumption-processed
    services_dir: node-consumption-services
    templates_dir: node-consumption-templates
  name: node-consumption
- data:
    output_dir: uhc-processed
    services_dir: uhc-services
    templates_dir: uhc-templates
  name: uhc
current: uhc
